### ISSUE TITLE
[REQUEST] Add More Cheat Detection For AC

### ISSUE THREAD

**Issue by proGaner69** [Bavfalcon9/Mavoric#38]
You can integrate more cheat detection for the AC like anti spam-bypass and TP aura (old cheat, still used today). Spider (wall climb type hack), chest purloiner, scaffolding, chest-larcenist, Anti-Velocity, Jesus, Item Physics, Follow (A bot that follows the most proximate entity), Anti-KnockBack, Multi aura (it’s obvious from the name), Trigger Bot, Fast Break. 
I hope this will avail with the development of the anti cheat. Many cheats are not listed here.

**Comment by Olybear9** [comment]
Thanks for the request!
Firstly, Multiaura is already implemented, however I plan to update it. Jesus is also implemented, but in development, as well as fastbreak detection. However from this request I will be adding:
 - AntiKB (AntiVelocity)
 - Scaffolding
 - Spider (Climbing walls)
 - TP Aura
 - Chest Aura (chest purloiner)

**Comment by Adam1609** [comment]
Well, it is impossible to say that PiggyCustomEnchants has Spider and Anti Knock Back which will cause major conflict if user install Mavoric into production servers.

**Comment by Olybear9** [comment]
It won't piggy CE sets the player to allow flight / can climb walls so it should be fine

**Comment by Olybear9** [comment]
@proGaner69 Follow is virtually impossible to detect on MCPE but I'll give it a shot, also i guess i could make an anti-spam feature, but this won't be my priority.

**Comment by Johnsonk79** [comment]
Just curious, how can scaffolding be possibly detected and prevented?

**Comment by Bavfalcon9** [comment]
@Johnsonk79 There's a few ways to do this, the most accurate would most likely be checking the angle of the block relative to the players yaw & pitch

**Comment by Johnsonk79** [comment]
But wouldn’t that be unreliable ecause of lag? ._.
