### ISSUE TITLE
[REQUEST] Disable all messages and report feature

### ISSUE THREAD

**Issue by EndermanLetsPlay** [Bavfalcon9/Mavoric#42]
Please add a feature that allows you to disable /mreport and all ingame messages when TPS drops down.

I'd be very glad! :)

**Comment by Olybear9** [comment]
Started working on in commit: https://github.com/Olybear9/Mavoric/commit/791e7397c137d8fe1f701168e86f01ccfe9cb0b4

**Comment by EndermanLetsPlay** [comment]
Many thanks for your support!
