### ISSUE TITLE
[BUG] MultiAura

### ISSUE THREAD

**Issue by ethaniccc** [Bavfalcon9/Mavoric#52]
## Description
If two players are basically near or grouped together, if hit around the same time, will flag it as MultiAura

**Additional context**
N/A

**Comment by Olybear9** [comment]
Known bug, for now disable the cheat.

**Comment by boi1216** [comment]
you could calculate difference between yaw between each movement update because killaura multiaura head rotation is mostly updated instantly by cheats

**Comment by Olybear9** [comment]
Snapcheck is already planned however there are some issues with it such as spinning in place with a fast mouse.

**Comment by VoltageMC** [comment]
Oly ill make a pull request for fixing entitys being counted in MultiAura, as it crashes the server when a player hits a lightning bolt from PiggyCes.

**Comment by Bavfalcon9** [comment]
This bug has been fixed on v2.0.0 as of commit: https://github.com/Bavfalcon9/Mavoric/commit/cd509addfea8cfd3107043f7aa0fd056fe945894
