### ISSUE TITLE
[REQUEST] kick hacker

### ISSUE THREAD

**Issue by ghost** [Bavfalcon9/Mavoric#67]
**Is your feature request related to a problem? Please describe.**

no

**Describe the solution you'd like**

why not make a configurable limit for each hack and when they exceed it kick them instead of only adding them to a ban wave then ban them?, this way it would provide much more options for servers with not so many players in it, if you were a hacker and you kept on getting kicked everytime you use a hack, you'll eventually fed up and turn it off.

**Describe alternatives you've considered**

none

**Additional context**

**Comment by Bavfalcon9** [comment]
Thank you for your suggestion! 
As of this commit: https://github.com/Bavfalcon9/Mavoric/commit/baf93e911a2830d2b48fe4b78b5c4bcb0d6ff5bc
I have started working on this suggestion.
