### ISSUE TITLE
[BUG] Reach and multi aura cause game to crash when trying to break a armour stand

### ISSUE THREAD

**Issue by Hellohi3654** [Bavfalcon9/Mavoric#69]
Whenever you try to destroy a armour stand with reach detection or multi aura detection on it causes a internal server error.

Please fix thanks

**Comment by Bavfalcon9** [comment]
Known issue with v1.0.x, this has been fixed in v2.0.0 or higher as of commit: https://github.com/Bavfalcon9/Mavoric/commit/8d29ecdb997ba6f54ab7a5077fca154944209fc3
